trigger:
  branches:
    include:
      - master
      - develop
  tags:
    include:
      - v*
pr:
  - master
  - develop

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    echo no | npm install -g nativescript
    ns usage-reporting disable
    ns error-reporting disable
  displayName: 'Install NativeScript CLI'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run lint
  displayName: 'Lint'

- script: |
    ns build android
  displayName: 'Build'

- script: |
    ./ci-tools/wait-for-emulator.sh
    ns test android --watch false --justlaunch
  displayName: 'Test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-reports/**/report.xml'
