// Add your native dependencies here:

dependencies {
//   coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.3'
  implementation 'com.squareup.okhttp3:okhttp:4.9.0'
}

// If you want to add something to be applied before applying plugins' include.gradle files
// e.g. project.ext.googlePlayServicesVersion = "15.0.1"
// create a file named before-plugins.gradle in the current directory and place it there

android {
  defaultConfig {
    minSdkVersion 23
	targetSdkVersion 34
    multiDexEnabled true
    generatedDensities = []
  }
  compileOptions {
    // Flag to enable support for the new language APIs
    // coreLibraryDesugaringEnabled true
    // Sets Java compatibility to Java 8
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}

allprojects {
  repositories {
       maven {
        url 'https://api.mapbox.com/downloads/v2/releases/maven'
        authentication {
            basic(BasicAuthentication)
        }
        credentials {
            // Do not change the username below.
            // This should always be `mapbox` (not your username).
            username = 'mapbox'
            // Use the secret token you stored in gradle.properties as the password
            password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: "REPLACE WITH YOUR SECRET TOKEN"
        }
    }
  }
}

// gradle.taskGraph.whenReady { taskGraph ->
//     taskGraph.allTasks.each { task ->
//         // Check for the desugaring task (l8DexDesugarLibDebug) and compileDebugArtProfile
//         if (task.name.contains("l8DexDesugarLibDebug") || task.name == 'compileDebugArtProfile') {
//             println "Desugaring or ART profile task detected: Disabling ART profile tasks"
//             tasks.matching { it.name.startsWith("compile") && it.name.endsWith("ArtProfile") }.configureEach {
//                 it.enabled = false
//                 println "Disabled ${it.name} due to desugaring"
//             }
//         }
//     }
// }
